//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmPresentation.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvvmPresentation.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;FullName&quot;:&quot;Прокопенко Иван&quot;},{&quot;Id&quot;:2,&quot;FullName&quot;:&quot;Харченко Мария &quot;},{&quot;Id&quot;:3,&quot;FullName&quot;:&quot;Викторовна Полина&quot;},{&quot;Id&quot;:4,&quot;FullName&quot;:&quot;Алямовский Михаил &quot;},{&quot;Id&quot;:5,&quot;FullName&quot;:&quot;Борисова Дарья &quot;},{&quot;Id&quot;:6,&quot;FullName&quot;:&quot;Останин Сергей &quot;},{&quot;Id&quot;:7,&quot;FullName&quot;:&quot;Марина Лебедева&quot;},{&quot;Id&quot;:8,&quot;FullName&quot;:&quot;Краснов Валерий&quot;},{&quot;Id&quot;:9,&quot;FullName&quot;:&quot;Пётр Иванов&quot;},{&quot;Id&quot;:10,&quot;FullName&quot;:&quot;Акимов Юрий&quot;}].
        /// </summary>
        internal static string CustomersJson {
            get {
                return ResourceManager.GetString("CustomersJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:98511361,&quot;Sum&quot;:1149.0000,&quot;Created&quot;:&quot;2024-10-29T14:21:53&quot;,&quot;CustomerId&quot;:9},{&quot;Id&quot;:98511408,&quot;Sum&quot;:1149.0000,&quot;Created&quot;:&quot;2024-10-29T14:24:48&quot;,&quot;CustomerId&quot;:9},{&quot;Id&quot;:98511714,&quot;Sum&quot;:566.0000,&quot;Created&quot;:&quot;2024-10-29T14:45:24&quot;,&quot;CustomerId&quot;:9},{&quot;Id&quot;:98511779,&quot;Sum&quot;:571.0000,&quot;Created&quot;:&quot;2024-10-29T14:49:25&quot;,&quot;CustomerId&quot;:9},{&quot;Id&quot;:98512003,&quot;Sum&quot;:1.0000,&quot;Created&quot;:&quot;2024-10-29T15:06:35&quot;,&quot;CustomerId&quot;:9},{&quot;Id&quot;:98512059,&quot;Sum&quot;:6365.0000,&quot;Created&quot;:&quot;2024-10-29T15:09:33&quot;,&quot;CustomerId&quot;:8},{&quot;Id&quot;:98512133,&quot;Sum&quot;:14617.0000,&quot;Created&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrdersJson {
            get {
                return ResourceManager.GetString("OrdersJson", resourceCulture);
            }
        }
    }
}
